"""rename assignee_id to assigned_to

Revision ID: fcc0624dc838
Revises: 97534c490646
Create Date: 2026-05-13 16:19:21.928381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc0624dc838'
down_revision: Union[str, Sequence[str], None] = '97534c490646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('tasks_assignee_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to'], ['id'])
    op.drop_column('tasks', 'assignee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assignee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_assignee_id_fkey'), 'tasks', 'users', ['assignee_id'], ['id'])
    op.drop_column('tasks', 'assigned_to')
    # ### end Alembic commands ###
